import type { Component } from 'svelte';
import { publishedLogEntries } from './generated/log-manifest';
import type { PublicLogMetadata } from './public-log-schema';

// The build-time log pipeline, the demo site's cells.ts pattern
// (greatfallstoolbus.org@origin/main src/lib/data/cells.ts) applied to the
// ratified spec §3 log schema. Every rendered surface — the home row, the
// /log archive and its pagination pages, the /log/<slug> permalinks, the
// sitemap — is driven by THIS module, so no surface can drift.
//
// B1 fix (PR #33 review): this module does NOT glob the content tree.
// src/lib/generated/log-manifest.ts (checked in, regenerated by
// `just log-manifest-build`, drift-checked by `just log-manifest-check`) is
// generated straight from node:fs over src/content/log/*.svx and contains
// ONLY entries with `published: true` — an unpublished draft's title,
// summary, or component is never an import anywhere this module (or
// anything that imports it, including client components) can reach. The
// published/draft split used to happen here, at RUNTIME, after an eager
// `import.meta.glob` had already made every draft a static import; that
// shipped full draft prose to every visitor (see docs/content-train.md and
// scripts/build-log-manifest.mjs for the full account).

export interface PublicLog {
	slug: string;
	metadata: PublicLogMetadata;
	/** Repo-relative .svx path, for the per-post SourceLink (#94 / B1.2). */
	sourcePath: string;
	/** Lazily resolves the entry's rendered body component (B1 fix). */
	loadComponent: () => Promise<{ default: Component }>;
}

/** Older entries per archive page (spec :90-91 pagination, no-JS path). */
export const LOG_PAGE_SIZE = 10;

/** One date formatter for every log surface (home row, archive, permalink). */
export const formatLogDate = (value: string): string =>
	new Intl.DateTimeFormat('en-US', { dateStyle: 'long', timeZone: 'UTC' }).format(new Date(`${value}T00:00:00Z`));

/** The 2026-08-11 entry's summary equals its title; never print a title twice. */
export const summaryDiffersFromTitle = (metadata: { title: string; summary: string }): boolean =>
	metadata.summary.trim() !== metadata.title.trim();

/**
 * Published entries only, newest first. Unpublished (`published: false`)
 * TODO(jess) drafts never reach this array — src/lib/generated/log-manifest.ts
 * excludes them at generation time, not by a runtime filter (spec §3: the
 * loader rejects unpublished entries in production output).
 */
export const publicLogs: PublicLog[] = [...publishedLogEntries].sort((left, right) =>
	right.metadata.date.localeCompare(left.metadata.date),
);

/** Archive pages after the first: /log is page 1, /log/page/<n> follow. */
export function logPageCount(): number {
	return Math.max(1, Math.ceil(publicLogs.length / LOG_PAGE_SIZE));
}

export function logPage(page: number): PublicLog[] {
	return publicLogs.slice((page - 1) * LOG_PAGE_SIZE, page * LOG_PAGE_SIZE);
}
